services:
  # ==================
  # PRODUCCION
  # ==================
  trip-app-back:
    profiles: ["prod"]
    container_name: trip-app-back
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime-prod
    env_file:
      - .env.prod
    expose:
      - "5030"
    volumes:
      - ./storage/uploads:/app/storage/uploads
      - /opt/static-sites/trips:/opt/static-sites/trips
    networks:
      appnet:
        ipv4_address: 172.18.0.7
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # ==================
  # DEV / TEST EN VPS
  # ==================
  trip-app-back-dev:
    profiles: ["dev"]
    container_name: trip-app-back-dev
    build:
      context: .
      dockerfile: Dockerfile
      target: runtime-test
    env_file:
      - .env.dev
    expose:
      - "5030"
    volumes:
      - ./storage/uploads:/app/storage/uploads
      - /opt/static-sites/trips:/opt/static-sites/trips
    networks:
      appnet:
        ipv4_address: 172.18.0.6
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "3"

networks:
  appnet:
    external: true
